[alias]
today = "run --quiet --release --features today -- today"
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"

solve = "run --quiet --release -- solve"
all = "run --quiet --release -- all"
time = "run --quiet --release -- time"

[env]
AOC_YEAR = "2024"
BINDGEN_EXTRA_CLANG_ARGS = "-I/opt/homebrew/Cellar/z3/4.13.3/include/ -L/opt/homebrew/Cellar/z3/4.13.3/lib"
LIBRARY_PATH = "/opt/homebrew/Cellar/z3/4.13.3/lib"
